CREATE ROLE t2s_readonly WITH LOGIN PASSWORD 't2s_readonly_pw';
GRANT CONNECT ON DATABASE text2sql TO t2s_readonly;
GRANT USAGE ON SCHEMA public TO t2s_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO t2s_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO t2s_readonly;
REVOKE CREATE ON SCHEMA public FROM t2s_readonly;
